# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FLITInvest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FLITInvest

  target 'FLITInvestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FLITInvestUITests' do
    # Pods for testing
  end

pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'Alamofire'
pod 'SnapKit'
pod 'KeychainSwift'
pod 'SwiftyJSON'
pod 'AppAuth'
pod 'BiometricAuthentication'

# Firebase
pod "Firebase/Auth"
pod "Firebase/Core"
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
end
